### ISSUE TITLE
Mais um decodificador TV

### ISSUE THREAD

**Issue by kpadilha** [offspringer/edgerouterx-vivo-fibra#1]
Boa noite! 
Obrigado pela configuração! Ajudou muito!
Um pergunta porém:
Posso colocar os decodificadores em outras portas que não a eth4? Ou preciso ajustar o PVID?

**Comment by offspringer** [comment]
Pode colocar em outras portas, mas deverá ajustar o PVID da porta desejada para 20. ;)
